# Generated by Django 4.2.5 on 2023-10-25 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auser',
        ),
    ]
