# Generated by Django 4.2.5 on 2023-10-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisement',
        ),
    ]
