# Generated by Django 4.2.5 on 2023-10-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0004_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default=1, upload_to='advertisement', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
