# Generated by Django 4.2.5 on 2023-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0006_alter_advertisement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisement/', verbose_name='Изображение'),
        ),
    ]
